#include <iostream>
using namespace std;
int main(){
// for(int i=0; i<=10; i++){      //Printing integer From 0 to 10 
//    cout<<i<<endl;
// }


//int count=1;
// while(count <=10){             //Printing integer From 0 to 10
//    cout<<count<<endl;
//    count++;
// }


   int count;
   cout<<"Enter Number: ";       
   cin>>count;
   if(count<10){                  //Checking Number is Smaller or Greater than 10
   cout<<"Number is Smaller than 10"<<endl;
   }
   else{
   cout<<"Number is Greater than 10"<<endl;
  }
}
