#include <iostream>
using namespace std;
int main (){
 int a,b;

cout<<"Enter First Value(a)- ";
cin>>a;
cout<<"Enter Second Value(b)- ";
cin>>b;
cout <<"Summation Of both Value- "<<a+b<<endl;           //Sum
cout <<"Differences Of Both Value- "<<a-b<<endl;         //Subtraction 
cout <<"Multiplication of both Value- "<<a*b<<endl;      //Multiplication 
cout<<"Quotient of A/B- "<<a/b<<endl;                    //Quotient 
cout<<"Remainder of A/B- "<<a%b<<endl;                   //Remainder
}  
 
